# Generated by Django 3.1 on 2021-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('songname', models.CharField(default='', max_length=50)),
                ('artist', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='mplayer/static')),
            ],
        ),
    ]
