# Generated by Django 3.1 on 2021-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(max_length=254, null=True, upload_to='mplayer/static/audio'),
        ),
    ]
